import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage();
 let writes=0,confirmed;
 const row={id:1,order:3,rowNumber:4,name:'Exercício teste',smartVideo:'',gymNamePt:'Teste',gymName:'Test',gymVideo:'',score:80,validated:false,comments:'',replacementTitle:'',replacementVideo:''};
 const current={validated:true,comments:'Comentário de outro professor',replacementTitle:'Outro título',replacementVideo:'https://example.com/video.mp4'};
 await page.route('**/api/reviews',async route=>{
  if(route.request().method()==='GET')return route.fulfill({json:{rows:[row],canEdit:true,updatedAt:new Date().toISOString()}});
  const body=route.request().postDataJSON();writes++;
  if(!body.confirmed)return route.fulfill({status:409,json:{error:'Já preenchido',code:'REVIEW_CONFIRMATION_REQUIRED',current}});
  confirmed=body;return route.fulfill({json:{row:{...row,...current,...body.patch}}});
 });
 await page.goto('http://127.0.0.1:5198');
 await page.getByLabel('Linha inicial',{exact:true}).fill('5');
 await page.getByText('Nenhum exercício encontrado.',{exact:false}).waitFor();
 await page.getByLabel('Linha inicial',{exact:true}).fill('4');
 await page.getByLabel('Linha final',{exact:true}).fill('4');
 await page.getByRole('heading',{name:'Exercício teste',exact:true}).waitFor();
 await page.getByLabel('Linha final',{exact:true}).fill('3');
 await page.getByText('A linha final deve ser maior ou igual à linha inicial.').waitFor();
 await page.getByRole('button',{name:'Limpar linhas'}).click();
 await page.locator('textarea').fill('Minha revisão');
 page.on('dialog',()=>assert.fail('Must not use browser confirmation'));
 await page.getByRole('button',{name:'Salvar revisão'}).click();
 const modal=page.getByRole('dialog',{name:'Confira antes de salvar'});
 await modal.waitFor();
 assert((await modal.innerText()).includes(current.comments));
 assert((await modal.innerText()).includes(current.replacementTitle));
 assert((await modal.innerText()).includes('Minha revisão'));
 assert.equal(await modal.locator('.review-diff.changed').count(),1);
 assert.equal(await modal.locator('.review-diff:not(.changed)').count(),3);
 await mkdir('../out/comparativo',{recursive:true});
 await page.screenshot({path:'../out/comparativo/confirmation-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'../out/comparativo/confirmation-mobile.png'});
 assert(await modal.evaluate(el=>el.scrollWidth<=el.clientWidth));
 await page.getByRole('button',{name:'Voltar à edição'}).click();
 await page.getByText('Gravação cancelada. Suas alterações continuam no formulário.').waitFor();
 assert.equal(writes,1);assert.equal(await page.locator('textarea').inputValue(),'Minha revisão');
 await page.getByRole('button',{name:'Salvar revisão'}).click();
 await modal.waitFor();
 await page.getByRole('button',{name:'Confirmar e salvar'}).click();
 await page.getByText('Salvo na planilha',{exact:true}).waitFor();
 assert.equal(writes,3);assert.deepEqual(confirmed.confirmed,current);assert.deepEqual(confirmed.patch,{comments:'Minha revisão'});
 assert(await page.getByLabel('Validado',{exact:true}).isChecked());
 await page.locator('textarea').fill('Mais uma revisão');
 await page.getByRole('button',{name:'Salvar revisão'}).click();
 await modal.waitFor();
 await page.keyboard.press('Escape');
 await page.getByText('Gravação cancelada. Suas alterações continuam no formulário.').waitFor();
 assert.equal(await page.locator('textarea').inputValue(),'Mais uma revisão');
 assert.equal(writes,4);
 await page.getByRole('button',{name:'Salvar revisão'}).click();
 await modal.waitFor();
 await page.screenshot({path:'../out/comparativo/confirmation-mobile.png'});
 await page.setViewportSize({width:1280,height:900});
 await page.screenshot({path:'../out/comparativo/confirmation-desktop.png'});
 await modal.getByRole('button',{name:'Descartar alterações',exact:true}).click();
 await page.getByText('Alterações descartadas. Exibindo os dados da planilha.').waitFor();
 assert.equal(await page.locator('textarea').inputValue(),current.comments);
 assert(await page.getByRole('button',{name:'Salvar revisão'}).isDisabled());
 assert.equal(writes,5);

 console.log('Browser: confirmation shows current data, cancel preserves draft, accept sends snapshot and only edited fields.');
} finally {await browser.close();}
