import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true,channel:"chrome"});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.locator('.simple-card').first().waitFor();
assert.equal(await page.locator('input[type=range]').count(),2);
assert.equal(await page.locator('input[type=checkbox],select').count(),0);
assert.equal(await page.getByText(/Simular compra|Simular custos|Selecionar vídeo/).count(),0);
const count=await page.locator('.simple-card').count();
await page.locator('.scroll-sentinel').scrollIntoViewIfNeeded();
await page.waitForFunction(n=>document.querySelectorAll('.simple-card').length>n,count);
await page.getByLabel('Similaridade mínima').fill('70');
await page.getByLabel('Similaridade máxima').fill('80');
await page.waitForTimeout(200);
const scores=await page.locator('.similarity-score').allTextContents();
assert(scores.length>0 && scores.every(v=>parseInt(v)>=70 && parseInt(v)<=80));
await page.getByLabel('Similaridade mínima').fill('0');
await page.getByLabel('Similaridade máxima').fill('100');
await page.evaluate(()=>window.scrollTo(0,0));
await page.waitForTimeout(4000);
const media=await page.locator('video').first().evaluate(v=>({autoPlay:v.autoplay,muted:v.muted,loop:v.loop,playing:!v.paused,time:v.currentTime}));
assert(media.autoPlay && media.muted && media.loop);
console.log({infiniteScroll:true,range:true,media,errors});
await page.screenshot({path:'../out/comparativo/simple-desktop.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../out/comparativo/simple-mobile.png'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.equal(await page.locator('nav[aria-label="Bibliotecas"] a').count(),1);
const search=page.getByRole('searchbox',{name:'Buscar exercício'});
await page.setViewportSize({width:1440,height:1000});
await search.fill('MÁQUINA lomb');
await page.waitForTimeout(150);
const accented=await page.locator('.simple-card h2').allTextContents();
assert(accented.length>0 && accented.every(t=>/lomb/i.test(t)));
await search.fill('  maquina   LOMB  ');
await page.waitForTimeout(150);
assert.deepEqual(await page.locator('.simple-card h2').allTextContents(),accented);
await search.fill('back extension');
await page.waitForTimeout(150);
assert(await page.locator('.simple-card').count()>0);
await page.getByLabel('Similaridade mínima').fill('80');
await page.waitForTimeout(150);
assert((await page.locator('.similarity-score').allTextContents()).every(v=>parseInt(v)>=80));
await search.fill('zzzinexistente');
await page.waitForTimeout(150);
assert.equal(await page.locator('.simple-card').count(),0);
await page.getByText('Nenhum exercício encontrado. Ajuste a busca ou a porcentagem.').waitFor();
await search.fill('');
await page.getByLabel('Similaridade mínima').fill('0');
await page.evaluate(()=>window.scrollTo(0,0));
await page.waitForTimeout(300);
await page.screenshot({path:'../out/comparativo/simple-desktop.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../out/comparativo/simple-mobile.png'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
console.log({search:true,accentAndCaseInsensitive:true,partialAndReorderedTerms:true,singleProvider:true});
assert.deepEqual(errors,[]);
await browser.close();
